name: Steering CI
on:
  push:
    paths:
      - 'Steering/**'
      - '.github/workflows/build_steering.yml'
  pull_request:
    paths:
      - 'Steering/**'
      - '.github/workflows/build_steering.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Linting (MISRA/Cppcheck)
      run: pio check -d Steering/Lucy_Dyn10 -e megaatmega2560 --skip-packages --fail-on-defect high

    - name: Build Firmware
      run: pio run -d Steering/Lucy_Dyn10 -e megaatmega2560

    - name: Run Unit Tests
      run: pio test -d Steering/Lucy_Dyn10 -e native
