name: PDM CI
on:
  push:
    paths:
      - 'PDM/**'
      - '.github/workflows/build_pdm.yml'
  pull_request:
    paths:
      - 'PDM/**'
      - '.github/workflows/build_pdm.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: pip install platformio

    - name: Linting (MISRA/Cppcheck)
      run: pio check -d PDM/PDM_FW -e esp32 --skip-packages --fail-on-defect high

    - name: Build Firmware
      run: pio run -d PDM/PDM_FW -e esp32

    - name: Run Unit Tests
      run: pio test -d PDM/PDM_FW -e native
